version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: carrierwave
    versions:
    - 1.3.2
    - 2.1.0
    - 2.2.0
  - dependency-name: puma
    versions:
    - 5.2.0
    - 5.2.1
  - dependency-name: delayed_job_active_record
    versions:
    - 4.1.5
